export FLASK_APP=main.py
export FLASK_DEBUG=1
export FLASK_RUN_PORT=8080
export FLASK_RUN_HOST=0.0.0.0
export SECRET_KEY=csc330
MAIL_USERNAME='OwlGoSCSU@gmail.com'
MAIL_APP_PASSWORD='Acces Token Here'
MAIL_SENDER_NAME='OwlGo'
