"""empty message

Revision ID: f55045b6ee79
Revises: 5619e413423f
Create Date: 2023-12-05 21:35:48.835927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f55045b6ee79'
down_revision = '5619e413423f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('report_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('ride_passenger',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_driver', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], ),
    sa.PrimaryKeyConstraint('ride_id', 'passenger_id')
    )
    op.create_table('ride_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('report_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('ride_request',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('commute_days', sa.String(length=50), nullable=True),
    sa.Column('accessibility', sa.String(length=100), nullable=True),
    sa.Column('custom_message', sa.String(length=500), nullable=True),
    sa.Column('requested_stops', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], ),
    sa.PrimaryKeyConstraint('ride_id', 'passenger_id')
    )
    op.drop_table('ride__passenger')
    op.drop_table('ride__report')
    op.drop_table('user__report')
    op.drop_table('ride__request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride__request',
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passenger_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('commute_days', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('accessibility', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('custom_message', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('requested_stops', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.user_id'], name='ride__request_ibfk_1'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], name='ride__request_ibfk_2'),
    sa.PrimaryKeyConstraint('ride_id', 'passenger_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user__report',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reported_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_text', mysql.TEXT(), nullable=True),
    sa.Column('report_timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.user_id'], name='user__report_ibfk_1'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.user_id'], name='user__report_ibfk_2'),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ride__report',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_text', mysql.TEXT(), nullable=True),
    sa.Column('report_timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], name='ride__report_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='ride__report_ibfk_2'),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ride__passenger',
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passenger_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_driver', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.user_id'], name='ride__passenger_ibfk_1'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.ride_id'], name='ride__passenger_ibfk_2'),
    sa.PrimaryKeyConstraint('ride_id', 'passenger_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ride_request')
    op.drop_table('ride_report')
    op.drop_table('ride_passenger')
    op.drop_table('user_report')
    # ### end Alembic commands ###
